options:
  install_sources:
    type: string
    default: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    description: apt repository to fetch beats from
  install_keys:
    type: string
    default: D88E42B4
    description: repository key
  logpath:
    type: string
    default: "/var/log/*.log /var/log/*/*.log"
    description: "Space separated log paths to monitor. Can contain wildcards."
  logging_to_syslog:
    type: boolean
    description: "Send filebeat logs to syslog https://www.elastic.co/guide/en/beats/filebeat/master/configuration-logging.html#_literal_to_syslog_literal"
    default: true
  logstash_hosts:
    type: string
    default: ""
    description: "A comma separated list of logstash output hosts in addition to those from relations."
  logstash_ssl_cert:
    type: string
    default: ""
    description: "Public SSL certificate data (base64 encoded) for connecting securely to logstash."
  logstash_ssl_key:
    type: string
    default: ""
    description: "Private SSL key data (base64 encoded) for connecting security to logstash."
  kafka_hosts:
    type: string
    default: ""
    description: "A comma separated list of kafka output hosts in addition to those from relations."
  kafka_topic:
    type: string
    default: "%{[type]}"
    description: "Topic name. Format strings are allowed. https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_literal_topic_literal"
  kafka_topics:
    type: string
    default: ""
    description: "Expert setting topics filter. https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_literal_topics_literal"
  kafka_version:
    type: string
    default: ""
    description: "Expert setting kafka version. https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_literal_version_literal"
  harvester_buffer_size:
    type: int
    default: 16384
    description: Defines the buffer size every harvester uses when fetching the file
  max_bytes:
    type: int
    default: 10485760
    description: Maximum number of bytes a single log event can have. Default 10MB
  exclude_files:
    type: string
    default: '[".gz$"]'
    description: A list of regular expressions to match the files that you want Filebeat to ignore. https://www.elastic.co/guide/en/beats/filebeat/5.3/configuration-filebeat-options.html#exclude-files
  exclude_lines:
    type: string
    default: "[]"
    description: A list of regular expressions to match the lines that you want Filebeat to exclude. https://www.elastic.co/guide/en/beats/filebeat/5.3/configuration-filebeat-options.html#exclude-lines
  fields:
    type: string
    default: ""
    description: "Space seperated list of key:value that the prospector will assign as field to each beat"
  kube_logs:
    type: boolean
    default: false
    description: "Add a prospector to ship logs from Kubernetes pods"
